#pragma once

#include <windows.h>

// IOCTL коды для Intel драйвера
#define IOCTL_INTEL_READ_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_WRITE_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_SPOOF_SERIALS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_HIDE_DRIVER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x903, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_CLEAN_TRACES CTL_CODE(FILE_DEVICE_UNKNOWN, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_INSTALL_HOOKS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_UNINSTALL_HOOKS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x906, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_GET_SPOOFED_DATA CTL_CODE(FILE_DEVICE_UNKNOWN, 0x907, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_BYPASS_ANTICHEAT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x908, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_SPOOF_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x909, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_FAKE_SYSTEM_CALLS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x90A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_HIDE_FROM_ANTICHEAT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x90B, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Структуры для Intel драйвера
typedef struct _INTEL_READ_MEMORY {
    ULONG64 Address;
    PVOID Buffer;
    ULONG Size;
} INTEL_READ_MEMORY, *PINTEL_READ_MEMORY;

typedef struct _INTEL_WRITE_MEMORY {
    ULONG64 Address;
    PVOID Buffer;
    ULONG Size;
} INTEL_WRITE_MEMORY, *PINTEL_WRITE_MEMORY;

typedef struct _INTEL_SPOOF_SERIALS {
    WCHAR BiosSerial[128];
    WCHAR BaseboardSerial[128];
    WCHAR SystemUUID[128];
    WCHAR DiskSerial[128];
    WCHAR CpuId[128];
    WCHAR MacAddress[128];
    WCHAR MachineGuid[128];
    WCHAR ProductId[128];
    WCHAR HardwareId[256];
    ULONG CpuFeatures;
    ULONG64 CpuFrequency;
    BOOLEAN EnableWmiHooks;
    BOOLEAN EnableSmbiosHooks;
    BOOLEAN EnableRegistryHooks;
    BOOLEAN EnableAntiCheatBypass;
    BOOLEAN EnableAdvancedHiding;
} INTEL_SPOOF_SERIALS, *PINTEL_SPOOF_SERIALS; 

typedef struct _INTEL_HIDE_DRIVER {
    BOOLEAN HideFromPsLoadedModuleList;
    BOOLEAN CleanMmUnloadedDrivers;
    BOOLEAN CleanPiDDBCacheTable;
    BOOLEAN RemoveRegistryTraces;
    BOOLEAN SelfDeleteFile;
    BOOLEAN HideFromDriverList;
    BOOLEAN HideFromServiceList;
} INTEL_HIDE_DRIVER, *PINTEL_HIDE_DRIVER;

typedef struct _INTEL_CLEAN_TRACES {
    BOOLEAN CleanEventLogs;
    BOOLEAN CleanPrefetch;
    BOOLEAN CleanTempFiles;
    BOOLEAN CleanRecentFiles;
    BOOLEAN CleanRegistryRunKeys;
    BOOLEAN CleanCrashDumps;
    BOOLEAN CleanAnticheatLogs;
} INTEL_CLEAN_TRACES, *PINTEL_CLEAN_TRACES;

typedef struct _INTEL_INSTALL_HOOKS {
    BOOLEAN HookWmiQuery;
    BOOLEAN HookSmbiosQuery;
    BOOLEAN HookRegistryQuery;
    BOOLEAN HookNtQuerySystemInformation;
    BOOLEAN HookNtQueryInformationProcess;
    BOOLEAN HookNtQueryInformationThread;
    BOOLEAN HookNtQueryInformationFile;
    BOOLEAN HookNtQueryInformationToken;
    BOOLEAN HookNtQueryInformationJobObject;
} INTEL_INSTALL_HOOKS, *PINTEL_INSTALL_HOOKS;

typedef struct _INTEL_UNINSTALL_HOOKS {
    BOOLEAN UninstallAllHooks;
} INTEL_UNINSTALL_HOOKS, *PINTEL_UNINSTALL_HOOKS;

typedef struct _INTEL_GET_SPOOFED_DATA {
    WCHAR RequestedData[128];
    WCHAR SpoofedValue[256];
    BOOLEAN Success;
} INTEL_GET_SPOOFED_DATA, *PINTEL_GET_SPOOFED_DATA;

typedef struct _INTEL_BYPASS_ANTICHEAT {
    BOOLEAN BypassBattlEye;
    BOOLEAN BypassEasyAntiCheat;
    BOOLEAN BypassVanguard;
    BOOLEAN BypassRicochet;
    BOOLEAN BypassFairFight;
    BOOLEAN HideFromProcessList;
    BOOLEAN HideFromModuleList;
    BOOLEAN FakeSystemCalls;
    BOOLEAN BypassXignCode3;
    BOOLEAN BypassGameGuard;
    BOOLEAN BypassPunkBuster;
    BOOLEAN BypassVAC;
} INTEL_BYPASS_ANTICHEAT, *PINTEL_BYPASS_ANTICHEAT;

typedef struct _INTEL_SPOOF_PROCESS {
    WCHAR ProcessName[64];
    WCHAR FakeProcessName[64];
    BOOLEAN HideProcess;
    BOOLEAN SpoofProcessId;
    ULONG FakeProcessId;
    BOOLEAN SpoofProcessPath;
    WCHAR FakeProcessPath[256];
} INTEL_SPOOF_PROCESS, *PINTEL_SPOOF_PROCESS;

typedef struct _INTEL_FAKE_SYSTEM_CALLS {
    BOOLEAN FakeNtQuerySystemInformation;
    BOOLEAN FakeNtQueryInformationProcess;
    BOOLEAN FakeNtQueryInformationThread;
    BOOLEAN FakeNtQueryInformationFile;
    BOOLEAN FakeNtQueryInformationToken;
    BOOLEAN FakeNtQueryInformationJobObject;
    BOOLEAN FakeNtQueryInformationPort;
    BOOLEAN FakeNtQueryInformationWorkerFactory;
} INTEL_FAKE_SYSTEM_CALLS, *PINTEL_FAKE_SYSTEM_CALLS;

typedef struct _INTEL_HIDE_FROM_ANTICHEAT {
    BOOLEAN HideFromBattlEye;
    BOOLEAN HideFromEAC;
    BOOLEAN HideFromVanguard;
    BOOLEAN HideFromRicochet;
    BOOLEAN HideFromFairFight;
    BOOLEAN HideFromXignCode3;
    BOOLEAN HideFromGameGuard;
    BOOLEAN HideFromPunkBuster;
    BOOLEAN HideFromVAC;
} INTEL_HIDE_FROM_ANTICHEAT, *PINTEL_HIDE_FROM_ANTICHEAT;

// Новые IOCTL коды для работы с виртуальной памятью
#define IOCTL_INTEL_TRANSLATE_VIRTUAL_ADDRESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x90F, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_GET_PROCESS_PEB CTL_CODE(FILE_DEVICE_UNKNOWN, 0x910, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_GET_PROCESS_DTB CTL_CODE(FILE_DEVICE_UNKNOWN, 0x911, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_READ_VIRTUAL_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x912, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_WRITE_VIRTUAL_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x913, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_READ_PROCESS_PEB CTL_CODE(FILE_DEVICE_UNKNOWN, 0x914, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INTEL_GET_PROCESS_MODULES CTL_CODE(FILE_DEVICE_UNKNOWN, 0x915, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Новые структуры для работы с виртуальной памятью
typedef struct _INTEL_VIRTUAL_ADDRESS_TRANSLATION {
    ULONG64 VirtualAddress;
    ULONG64 PhysicalAddress;
    BOOLEAN Success;
} INTEL_VIRTUAL_ADDRESS_TRANSLATION, *PINTEL_VIRTUAL_ADDRESS_TRANSLATION;

typedef struct _INTEL_PROCESS_PEB_INFO {
    ULONG ProcessId;
    ULONG64 PEBAddress;
    ULONG64 DirectoryTableBase;
    BOOLEAN Success;
} INTEL_PROCESS_PEB_INFO, *PINTEL_PROCESS_PEB_INFO;

typedef struct _INTEL_VIRTUAL_MEMORY_OPERATION {
    ULONG ProcessId;
    ULONG64 VirtualAddress;
    PVOID Buffer;
    SIZE_T Size;
    BOOLEAN IsRead;
} INTEL_VIRTUAL_MEMORY_OPERATION, *PINTEL_VIRTUAL_MEMORY_OPERATION;

typedef struct _INTEL_PROCESS_MODULES_INFO {
    ULONG ProcessId;
    PVOID ModuleList;
    SIZE_T BufferSize;
    ULONG ModuleCount;
    BOOLEAN Success;
} INTEL_PROCESS_MODULES_INFO, *PINTEL_PROCESS_MODULES_INFO; 